# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 02:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 1, 17, 2, 21, 40, 936430, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
