# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170116_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='draft',
            new_name='borrador',
        ),
    ]
